[package]
name = "gitui"
version = "0.10.1"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
exclude = [".github/*",".vscode/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = [
    "git",
    "gui",
    "cli",
    "terminal",
    "ui",
]

[dependencies]
scopetime = { path = "./scopetime", version = "0.1" }
asyncgit = { path = "./asyncgit", version = "0.10" }
crossterm = { version = "0.18", features = [ "serde" ] }
clap = { version = "2.33", default-features = false }
tui = { version = "0.9", default-features = false, features = ['crossterm'] }
bytesize = { version = "1.0.1", default-features = false}
itertools = "0.9"
rayon-core = "1.8"
log = "0.4"
simplelog = { version = "0.8", default-features = false }
dirs = "3.0"
crossbeam-channel = "0.4"
scopeguard = "1.1"
bitflags = "1.2"
chrono = "0.4"
backtrace = "0.3"
ron = "0.6"
serde = "1.0"
anyhow = "1.0.32"
unicode-width = "0.1"
textwrap = "0.12"
clipboard = { version = "0.5", optional = true }

[target.'cfg(not(windows))'.dependencies]
pprof = { version = "0.3", features = ["flamegraph"], optional = true }

[badges]
maintenance = { status = "actively-developed" }

[features]
default=["clipboard"]
timing=["scopetime/enabled"]

[workspace]
members=[
    "asyncgit",
    "scopetime",
]

[profile.release]
lto = true
opt-level = 'z'  # Optimize for size.
codegen-units = 1
